include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - slash_for_doc_comments
    - sort_constructors_first
    - unnecessary_brace_in_string_interps
    - cancel_subscriptions
    - unnecessary_new
    - prefer_is_empty
    - prefer_is_not_empty

analyzer:
#   exclude:
#     - path/to/excluded/files/**