name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  intl: ^0.15.7
  rxdart: ^0.19.0

  json_annotation: ^2.0.0
  shared_preferences: ^0.4.3
  email_validator: ^1.0.0
  url_launcher: ^5.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  pedantic: ^1.7.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bg_splash.png
    - assets/images/ic_empty.png
    - assets/images/ic_head_big.png
    - assets/images/ico_cjxx_kg_dis.png
    - assets/images/ico_cjxx_kg_g.png
    - assets/images/ico_cjxx_kg_k.png
    - assets/images/ico_dh.png
    - assets/images/ico_fh.png
    - assets/images/ico_htxq_jt_s.png
    - assets/images/ico_htxq_jt_x.png
    - assets/images/ico_lb_ry.png
    - assets/images/ico_lb_tj.png
    - assets/images/ico_lb_tj_gray.png
    - assets/images/ico_lb_tjkh.png
    - assets/images/ico_me_jt.png
    - assets/images/ico_me_mm.png
    - assets/images/ico_me_tc.png
    - assets/images/ico_me_tx.png
    - assets/images/ico_rb_rq.png
    - assets/images/ico_rb_tj.png
    - assets/images/ico_ry.png
    - assets/images/ico_rz.png
    - assets/images/ico_rz_xz.png
    - assets/images/ico_ss.png
    - assets/images/ico_sx.png
    - assets/images/ico_sx_jt_s.png
    - assets/images/ico_sx_jt_x.png
    - assets/images/ico_sy.png
    - assets/images/ico_sy_kh.png
    - assets/images/ico_sy_xs.png
    - assets/images/ico_sy_xz.png
    - assets/images/ico_tj.png
    - assets/images/ico_tk_guanbi.png
    - assets/images/ico_wd.png
    - assets/images/ico_wd_xz.png
    - assets/images/ico_xq_fz.png
    - assets/images/ico_xq_sc.png
    - assets/images/ico_xq_tj.png
    - assets/images/ico_xq_xs_jrsh.png
    - assets/images/ico_xq_yq.png
    - assets/images/ico_xq_zd_xz.png
    - assets/images/ico_xq_zwkh.png
    - assets/images/ico_zd.png
    - assets/images/ico_zd_checked.png
    - assets/images/p_me.png
    - assets/images/p_sy.png
    - assets/images/rili.png
    - assets/images/ico_sy_k.png
    - assets/images/ico_dl_logo.png
    - assets/images/ico_tx.png
    - assets/images/ico_wdrb_jt_y.png
    - assets/images/ico_wdrb_jt_z.png
    - assets/images/ico_rb_pl.png
    - assets/images/ico_xx.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
